### ISSUE TITLE
genna on go-pg v9

### ISSUE THREAD

**Issue by taiyangc** [dizzyfool/genna#26]
go-pg v9 has migrated all struct field tags with `sql:` to `pg:` [[ref]](https://github.com/go-pg/pg/blob/master/CHANGELOG.md#v9)

But the current example at https://github.com/dizzyfool/genna/blob/master/generators/model/README.md still shows `sql:`. Is it just the example wrong or genna hasn't fully migrated yet? I am currently unable to test this out due to #25 Thanks.

**Comment by dizzyfool** [comment]
Hey @taiyangc 
Readme is a bit outdated, I'll try to make it more informative in future.

In your particular case: you can generate model that will work with go-pg v9 - just use `-g=9` or `--gopg=9` flag. This way genna will generate `pg` tag instead of `sql`, `use_zero` instead of `notnull` v9 models is still not fully tested, so feel free to report a bugs if you find any.

**Comment by dizzyfool** [comment]
#25 fixed

**Comment by taiyangc** [comment]
`-g=9` works, thanks.
